---
name: Docker Build - Simple
# simplest workflow possible
# based on Docker's official GitHub Actions and their Docs:
#   https://docs.docker.com/build/ci/github-actions/

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    # we ALWAYS want to define what permissions we need
    # this will avoid errors if your org/repo settings are more strict
    permissions:
      packages: write # needed to push docker image to ghcr.io

    steps:        
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # NOTE: github.actor is the username of the person who triggered the workflow
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          # only push image when we merge PRs or push to main branch
          push: ${{ github.event_name != 'pull_request' }}
          # hardcoded for a single name/tags
          tags: ghcr.io/hardlydevops/wordsmith-web:latest
